FROM docker.io/library/golang:latest AS builder
ENV GOCACHE="/go/.cache"
ENV GOMODCACHE="/go/pkg/mod"
WORKDIR /cluster-debug-tools
RUN --mount=type=cache,target=/go/.cache \
    --mount=type=cache,target=/go/pkg/mod \
  CGO_ENABLED=0 GOBIN=/usr/local/bin go install github.com/openshift/cluster-debug-tools/cmd/kubectl-dev_tool@latest

FROM scratch AS final
COPY --from=builder /usr/local/bin/ /usr/local/bin/
