FROM docker.io/library/golang:latest AS builder
ENV GOCACHE="/go/.cache"
ENV GOMODCACHE="/go/pkg/mod"
WORKDIR /cluster-debug-tools
RUN --mount=type=cache,target=/go/.cache \
    --mount=type=cache,target=/go/pkg/mod \
  GOBIN=/cluster-debug-tools go install github.com/openshift/cluster-debug-tools/cmd/kubectl-dev_tool@latest

FROM quay.io/fedora/fedora:42 AS final
COPY --from=builder /cluster-debug-tools /cluster-debug-tools
