FROM docker.io/library/golang:latest AS builder
WORKDIR /out
WORKDIR /mco
ENV GOCACHE="/go/.cache"
ENV GOMODCACHE="/go/pkg/mod"
RUN --mount=type=cache,target=/go/.cache \
    --mount=type=cache,target=/go/pkg/mod \
    git clone --depth=1 https://github.com/openshift/machine-config-operator.git . && \
    make -j install-helpers DESTDIR=/out

FROM quay.io/fedora/fedora:42 AS final
COPY --from=builder /out /mco
